### ISSUE TITLE
##[error]One of your files includes an unsupported file status renamed, expected 'added', 'modified', or 'removed'.

### ISSUE THREAD

**Issue by rowi1de** [jitterbit/get-changed-files#3]
Is this known?

##[error]One of your files includes an unsupported file status renamed, expected 'added', 'modified', or 'removed'.

**Comment by sean-krail** [comment]
Thanks for reporting. I’ll look into it this week.

**Comment by sean-krail** [comment]
@rowi1de this should be fixed now in `jitterbit/get-changed-files@v1`. Let me know if this is fixed for you and I'll close the ticket!

**Comment by rowi1de** [comment]
Thanks for looking into it, will test it today

**Comment by rowi1de** [comment]
Works as expected 👍
