### ISSUE TITLE
Get changes from master branch on each commit

### ISSUE THREAD

**Issue by lgabs** [jitterbit/get-changed-files#5]
I'm pretty beginner on github actions, but so far this action is very useful, thank you!

What I'm facing is the following situation:
-  open a PR with commit n1, with some condition on changed files that triggers some important job j1 to fail
-  commit again (n2) changing other files that does not trigger job #1, making checks to pass
- the PR so far is passing on checks with both commits, but should not be merged since commit #1 did not make job j1 pass.

I've seen that the base commit used is the previous, so new commits on PR are compared just against previous one, not master branch. Is there a way to compare master and all PR's commit on each new change to avoid this?

**Comment by sean-krail** [comment]
Hi @lgabs, so if I understand this correctly you have a PR open from base commit B with two commits C1 and C2. The check suite using this action failed for C1 (getting changed files from B to C1) and passed for C2 (getting changed files from B to C2). The way GitHub works is that at this point your PR is passing the checks and is ready for merge.

> I've seen that the base commit used is the previous, so new commits on PR are compared just against previous one

This shouldn't be the case. Can you reproduce this in a public repo so I can see? We use this action internally and haven't experienced it.

**Comment by sean-krail** [comment]
@lgabs, is this still an issue? If not, I'll close this ticket. Thanks!

**Comment by lgabs** [comment]
Hi, Sean! I finally understood... You were right, and indeed I could not reproduce the problem. If I see any thing strange like that again, I'll come back to this, so we can close it.
