### ISSUE TITLE
Error: a step cannot have both the `uses` and `run` keys

### ISSUE THREAD

**Issue by wbt** [jitterbit/get-changed-files#50]
When trying to follow along with the example, I noticed that both the 'uses' and 'run' keys are present and copying that into a yml file, I get an error from GitHub that "a step cannot have both the `uses` and `run` keys".
Following the example exactly works, but not if the run component calls a command to run an external script. 
It may be helpful to update documentation to show an example of e.g. calling a Node script.

**Comment by Amir-Hadadi** [comment]
Encountered this too

**Comment by wbt** [comment]
I think this was because I missed the dash in front of the run key, which makes it a separate step.
